# Generated by Django 3.2.9 on 2022-01-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssessmentSystem', '0003_auto_20211220_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='expenses_details',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='expenses',
            name='expenses_name',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='users',
            name='firstname',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='lastname',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='phonenumber',
            field=models.CharField(max_length=13),
        ),
    ]
