# Generated by Django 3.2.9 on 2022-01-03 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssessmentSystem', '0004_auto_20220103_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='plan_details',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
