# Generated by Django 4.0.1 on 2022-01-07 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AssessmentSystem', '0007_auto_20220103_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='plan_details',
            new_name='plan_name',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='expenses_details',
        ),
        migrations.RemoveField(
            model_name='income',
            name='income_date',
        ),
        migrations.RemoveField(
            model_name='income',
            name='income_source',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='plans',
        ),
    ]
