# Generated by Django 4.0.1 on 2022-01-08 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AssessmentSystem', '0008_rename_plan_details_plan_plan_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='id',
        ),
        migrations.RemoveField(
            model_name='users',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='users',
            name='lastname',
        ),
        migrations.AddField(
            model_name='income',
            name='plan_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AssessmentSystem.plan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AssessmentSystem.users'),
            preserve_default=False,
        ),
    ]
