# Generated by Django 4.0.1 on 2022-01-10 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AssessmentSystem', '0010_plan_plan_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='plan_id',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='AssessmentSystem.plan'),
        ),
    ]
