# Generated by Django 4.0.1 on 2022-01-10 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AssessmentSystem', '0011_alter_expenses_plan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='plan_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssessmentSystem.plan'),
        ),
    ]
