# Generated by Django 4.0.1 on 2022-01-11 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AssessmentSystem', '0012_alter_expenses_plan_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='plan_detail',
            new_name='plan_details',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='user',
        ),
        migrations.AddField(
            model_name='users',
            name='lastname',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='income',
            name='plan_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
