# Generated by Django 4.0.1 on 2022-01-11 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AssessmentSystem', '0013_rename_plan_detail_plan_plan_details_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='lastname',
            new_name='middle_name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='middlename',
        ),
    ]
